version: 0.2
env:
  shell: bash
  variables:
    AWS_DEFAULT_REGION: "us-west-2"
    IMAGE_REPO_NAME: "skiapp"
    AWS_ACCOUNT_ID: "180287136233"
  exported-variables:
   - IMAGE_TAG
  
phases:
  pre_build:
    commands:
      - echo Setting up image tag
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)
      - echo $COMMIT_ID
      - IMAGE_TAG=dev-$COMMIT_ID-$CODEBUILD_BUILD_NUMBER
      - echo $IMAGE_TAG
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - aws codebuild start-build --project-name "test" --region "us-west-2" --environment-variables-override name=GIT_BRANCH,value=main,type=PLAINTEXT name=IMAGE_TAG,value=$IMAGE_TAG,type=PLAINTEXT
cache: 
  type: LOCAL
  modes: LOCAL_DOCKER_LAYER_CACHE
