version: 0.2
env:
  shell: bash
  variables:
    AWS_DEFAULT_REGION: "us-west-2"
    MAJOR: "1"
    MINOR: "0"
    IMAGE_REPO_NAME: "skiapp"
    AWS_ACCOUNT_ID: "180287136233"
  exported-variables:
   - IMAGE_TAG
  
phases:
  pre_build:
    commands:
      - echo Setting up image tag
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)
      - echo $COMMIT_ID
      - echo $GIT_BRANCH
      - |
        if [[ "${GIT_BRANCH}" == "develop" ]]; then
           IMAGE_TAG=$GIT_BRANCH-$COMMIT_ID-$CODEBUILD_BUILD_NUMBER
        elif [[ "${GIT_BRANCH}" == "main" ]]; then
           IMAGE_TAG="v${MAJOR}.${MINOR}.${CODEBUILD_BUILD_NUMBER}"
        fi
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - |
        if [[ "${GIT_BRANCH}" == "develop" ]]; then
          echo Building the Docker image...          
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          aws ssm put-parameter --name "/Ski_App/Image_Tag" --type "String" --value "${IMAGE_TAG}" --overwrite
        elif [[ "${GIT_BRANCH}" == "main" ]]; then
          EXISTING_IMAGE_TAG=$(aws ssm get-parameter --name "/Ski_App/Image_Tag" --output text --query Parameter.Value)
          MANIFEST=$(aws ecr batch-get-image --repository-name $IMAGE_REPO_NAME --image-ids imageTag=$EXISTING_IMAGE_TAG --output json | jq --raw-output --join-output '.images[0].imageManifest')
          aws ecr put-image --repository-name $IMAGE_REPO_NAME --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"  
        fi
  post_build:
    commands:
      - |
        if [[ "${GIT_BRANCH}" == "develop" ]]; then
          echo Build completed on `date`
          echo Pushing the Docker image...
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        fi
      - aws codebuild start-build --project-name "cd-automation" --region "us-west-2" --environment-variables-override name=GIT_BRANCH,value=$GIT_BRANCH,type=PLAINTEXT name=IMAGE_TAG,value=$IMAGE_TAG,type=PLAINTEXT
cache: 
  type: LOCAL
  modes: LOCAL_DOCKER_LAYER_CACHE
